#!/bin/bash
flag="/etc/oobe"

if [[ ! -f "$flag" ]] ; then
  /bin/bash /bin/oobe.sh > /var/log/oobe.log
  touch "$flag"
fi

nm-applet&
MB_KBD_CONFIG=/usr/share/matchbox-keyboard/keyboard.xml matchbox-keyboard -d &
