name: Dev Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Requirements
      run: sudo apt update; sudo apt install -y qemu-user-static debootstrap

    - name: Debootstrap
      run: sudo qemu-debootstrap --no-check-gpg --arch=armel stretch ./rootfs ftp://ftp.nl.debian.org/debian/

    - name: Copy additional files
      run: yes | sudo cp -r ./shared/rootfs/* ./rootfs/

    - name: Apply flags
      run: sudo chmod +x ./rootfs/etc/X11/icewm/startup

    - name: Run apt update
      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; apt update'

    - name: Run apt upgrade
      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; apt upgrade -y'

#    - name: Install locales
#      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; apt install locales -y'

#    - name: Setup locales
#      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export LC_ALL=C; echo "LANG=\"en_US.UTF-8\"" > /etc/default/locale; export LANGUAGE=en_US.UTF-8; export LANG=en_US.UTF-8; update-locale "LANG=en_US.UTF-8"; locale-gen --purge "en_US.UTF-8"; dpkg-reconfigure --frontend noninteractive locales'

    - name: Setup additional packages
      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; DEBIAN_FRONTEND=noninteractive apt install icewm xinit xterm dillo xfe connman-ui libfakekey0 -y'

    - name: Setup icewm autostart
      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; systemctl enable xinit.service'

    - name: Setup root password
      run: sudo chroot ./rootfs /bin/bash -c 'export PATH="/usr/sbin:/usr/bin:/sbin:/bin"; echo -e "toor\ntoor" | passwd root'

    - name: Pack to tar
      run: sudo tar --create --ignore-failed-read --preserve-permissions --recursion --sparse --totals --wildcards --verbose --gzip --file=rootfs.tar.gz ./rootfs/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-${{ github.sha }}
        prerelease: true
        name: Dev build ${{ github.sha }}
        files: |
          rootfs.tar.gz

